collector_plate = OpenStudio::Model::SolarCollectorFlatPlateWater.new(model)
collector_plate.setName(obj_name + ' coll plate')
collector_plate.setSurface(shading_surface)
collector_plate.setMaximumFlowRate(UnitConversions.convert(coll_flow, 'cfm', 'm^3/s'))
collector_performance = collector_plate.solarCollectorPerformance
collector_performance.setName(obj_name + ' coll perf')
collector_performance.setGrossArea(UnitConversions.convert(solar_thermal_system.collector_area, 'ft^2', 'm^2'))
collector_performance.setTestFluid('Water')
collector_performance.setTestFlowRate(UnitConversions.convert(coll_flow, 'cfm', 'm^3/s'))
collector_performance.setTestCorrelationType('Inlet')
collector_performance.setCoefficient1ofEfficiencyEquation(solar_thermal_system.collector_frta)
collector_performance.setCoefficient2ofEfficiencyEquation(-UnitConversions.convert(solar_thermal_system.collector_frul, 'Btu/(hr*ft^2*F)', 'W/(m^2*K)'))
collector_performance.setCoefficient2ofIncidentAngleModifier(-iam_coeff2)
collector_performance.setCoefficient3ofIncidentAngleModifier(iam_coeff3)
